### ISSUE TITLE
Setting the frame rate

### ISSUE THREAD

**Issue by asprasan** [cedric-scheerlinck/dvs_image_reconstruction#5]
I am trying to reconstruct images from an existing DAVIS dataset using the Complementary Filter. I would like to vary the frame rate of the reconstructed images. I am thinking that to vary the frame rate I will have to vary the value of the variable `global_log_intensity_state_update_frequency` in the file `from_rosbag.launch`. However, I found that the frame rate is not going beyond 30 frames/s. Here, I found the frame rate by saving the reconstructed frames with the timestamp as its filename, where `timestamp` is given as an input to the function `publish_intensity_estimate`.

Thanks in advance.

**Comment by asprasan** [comment]
Can you help me with this? Is there anything I am missing? Any variables which I need to set? Your help will be greatly appreciated.

**Comment by cedric-scheerlinck** [comment]
Hello, sorry for late reply.

You are not missing any variables. At the moment you can only publish an image once per event message. This means that if the event messages are at 30hz, you will notice the output images at 30hz.

As a temporary fix you can try to repackage the bag to have a higher frequency of event messages.

I will try to update the code this week to allow for arbitrary framerates and better interface for saving images.

**Comment by cedric-scheerlinck** [comment]
I have updated the code and you should be able to directly read rosbags (without having the use rosbag play...) and save images, in addition to setting arbitrary publishing framerates (etiher using command-line flag publish_framerate:=<number> or in the .launch file by changing the publish_framerate parameter). In the src code the variable is named publish_framerate_.

**Comment by asprasan** [comment]
Thank you very much.
